/**
 * Status map — nguồn sự thật: (status string) → semantic tone.
 * Sinh từ object TONE trong components-preview.html (đã auto-gen từ mock-data.ts).
 * 101 giá trị distinct, phủ đủ 26 domain union.
 *
 * Priority: special > danger > positive > warning > info > muted > neutral
 * (CLAUDE.md + FRONTEND-AI-RULES.md §6.1)
 */

import type { SemanticTone } from "@/lib/mock-data";

export type { SemanticTone };

const TONE: Record<SemanticTone, readonly string[]> = {
  positive: [
    "DELIVERED",
    "CONFIRMED",
    "RECEIVED",
    "Confirmed",
    "Approved",
    "APPROVED",
    "Completed",
    "Delivered",
    "Packed",
    "Received",
    "Active",
    // Biến thể (BE VariantStatus, PR #71)
    "ACTIVE",
    "Paid",
    "Matched",
    "Accepted",
    "Pass",
    "In stock",
    "Reviewed",
    "Converted",
    "Authorized",
    "Captured",
    "Available",
    "Occupied",
    "Resolved",
    "Refund Issued",
    "Exchange Shipped",
    "Item Received",
    "Partially Received",
    "Handed to Shipping",
    "Ready to Dispatch",
    "Staged",
    "Picked",
    "Allocated",
  ],
  info: [
    "QUEUED",
    "SENT",
    "In Progress",
    "In Transit",
    "Picking",
    "Shipped",
    "Assigned",
    "Released",
    "Published",
    "In Putaway",
    "Partially Fulfilled",
    "Partially Completed",
    "Out for Delivery",
    "Pending (COD)",
    "Reserved",
    "Ready",
    "Locked",
    "Handed Over",
    "Queued",
    "Approved for Payment",
    "Initiated",
    // Order — BE IN_FULFILMENT (picking/packing/sản xuất gộp làm 1). FE order khớp BE.
    "In Fulfilment",
  ],
  warning: [
    "RETRYING",
    "PENDING",
    "PARTIALLY_RECEIVED",
    "PENDING_APPROVAL",
    "Pending Approval",
    "On Hold",
    "Exception",
    "Short",
    "Discrepancy",
    "Quarantine",
    "Blocked",
    "BLOCKED",
    "Low stock",
    "Awaiting Confirmation",
    "Verification Failed",
    "Escalated",
    "Inbound",
    "Reopened",
    "Waiting on Customer",
    "Waiting on Internal",
    "Partially Paid",
    "Warning",
    "Pending Payment",
    "Ready to Fulfill",
    "Return Requested",
    "Pending Verification",
    "Draft Proposal",
    // Receipt — còn dòng cần QC chưa kết luận, chặn putaway (docs 03 §5.1)
    "In QC",
  ],
  danger: [
    "Blacklisted",
    "FAILED",
    "REJECTED",
    "CANCELLED",
    "Cancelled",
    "Rejected",
    "Failed",
    "Disputed",
    "Delivery Failed",
    "Returned",
    "Returning",
    "Suspended",
    "Out of stock",
    "Fail",
    "Obsolete",
    "OBSOLETE",
    "Payment Failed",
    "Unpaid",
    "Timeout",
  ],
  neutral: [
    "NOT_SENT",
    "DRAFT",
    "Draft",
    "Created",
    "Pending",
    "Label Created",
    "Suggested",
    "Guest",
    "New",
    "Requested",
  ],
  muted: [
    "UNKNOWN",
    "SUPPRESSED",
    // BE #36 cancellationDeliveryStatus: PO huỷ trước khi gửi NCC → không cần báo huỷ.
    "NOT_REQUIRED",
    "CLOSED",
    "Closed",
    "Inactive",
    "Hidden",
    "Unpublished",
    "Anonymized",
    "Merged",
    "Voided",
    "Superseded",
    "Empty",
    "Full",
    "Disabled",
    "Archived",
    "Discontinued",
    "Abandoned",
    // QC dòng nhận — SKU không bật cờ Yêu cầu QC, đi luồng 2 bước (docs 03 §5.2)
    "Not Required",
  ],
  special: ["Refunded", "Partially Refunded", "In Production"],
};

/** Thứ tự ưu tiên khi status trùng nhiều tone (CLAUDE.md). */
const PRIORITY: readonly SemanticTone[] = [
  "special",
  "danger",
  "positive",
  "warning",
  "info",
  "muted",
  "neutral",
];

/** Tra tone cho một status string. Fallback = neutral. */
export function toneOf(status: string): SemanticTone {
  for (const t of PRIORITY) {
    if ((TONE[t] as readonly string[]).includes(status)) return t;
  }
  return "neutral";
}

/** Nhãn tiếng Việt cho status (song ngữ hiển thị trong tooltip/title). */
export const STATUS_LABEL_VI: Record<string, string> = {
  // PO — BE D4 (PR #71). CONFIRMED = đã chốt và gửi NCC; dùng chung nhãn với phản hồi NCC.
  DRAFT: "Nháp",
  PENDING_APPROVAL: "Chờ duyệt",
  APPROVED: "Đã duyệt",
  PARTIALLY_RECEIVED: "Nhận một phần",
  RECEIVED: "Đã nhận đủ",
  CLOSED: "Đã đóng",
  CANCELLED: "Đã huỷ",
  // Lần gửi NCC (DeliveryAttempt.status). Trạng thái PO cũ (SENT, CLOSED_SHORT) BE PR #71 đã
  // chuyển sang D4 cả trong lịch sử — đóng thiếu là CLOSED + closeKind SHORT_CLOSE.
  SENT: "Đã gửi NCC",
  // PO — trạng thái gửi NCC (BE deliveryStatus / DeliveryAttempt.status) + NCC phản hồi
  // (BE supplierConfirmationStatus). PENDING dùng chung cho "chờ gửi" và "chờ NCC phản hồi".
  NOT_SENT: "Chưa gửi",
  QUEUED: "Đang chờ gửi",
  RETRYING: "Đang gửi lại",
  FAILED: "Gửi thất bại",
  DELIVERED: "Đã gửi tới NCC",
  UNKNOWN: "Không rõ",
  SUPPRESSED: "Đã chặn gửi",
  NOT_REQUIRED: "Không cần báo huỷ",
  PENDING: "Đang chờ",
  CONFIRMED: "Đã xác nhận",
  REJECTED: "NCC từ chối",
  // Positive
  Confirmed: "Đã xác nhận",
  Approved: "Đã duyệt",
  Completed: "Hoàn tất",
  Delivered: "Đã giao",
  Packed: "Đã đóng gói",
  Received: "Đã nhận",
  Active: "Hoạt động",
  ACTIVE: "Đang dùng",
  Paid: "Đã thanh toán",
  Matched: "Khớp",
  Accepted: "Chấp nhận",
  Pass: "Đạt",
  "In stock": "Còn hàng",
  Reviewed: "Đã xem xét",
  Converted: "Đã chuyển đổi",
  Authorized: "Đã ủy quyền",
  Captured: "Đã thu tiền",
  Available: "Khả dụng",
  Occupied: "Đang chiếm",
  Resolved: "Đã giải quyết",
  "Refund Issued": "Đã hoàn tiền",
  "Exchange Shipped": "Đã gửi hàng đổi",
  "Item Received": "Đã nhận hàng",
  "Partially Received": "Nhận một phần",
  "Handed to Shipping": "Bàn giao vận chuyển",
  "Ready to Dispatch": "Sẵn sàng xuất",
  Staged: "Tập kết",
  Picked: "Đã lấy",
  Allocated: "Đã phân bổ",
  // Info
  "In Progress": "Đang xử lý",
  "In Transit": "Đang vận chuyển",
  Picking: "Đang lấy hàng",
  Shipped: "Đã gửi",
  Assigned: "Đã gán",
  Released: "Đã release",
  Published: "Đã xuất bản",
  "In Putaway": "Đang cất",
  "In QC": "Đang kiểm QC",
  "Not Required": "Không cần QC",
  "Partially Fulfilled": "Thực hiện một phần",
  "Partially Completed": "Hoàn thành một phần",
  "Out for Delivery": "Đang giao",
  "Pending (COD)": "Chờ COD",
  Reserved: "Đã giữ",
  Ready: "Sẵn sàng",
  Locked: "Đã khóa",
  "Handed Over": "Đã bàn giao",
  Queued: "Trong hàng đợi",
  "Approved for Payment": "Duyệt thanh toán",
  Initiated: "Đã khởi tạo",
  "In Production": "Đang sản xuất",
  "In Fulfilment": "Đang xử lý kho",
  // Warning
  "Pending Approval": "Chờ duyệt",
  "On Hold": "Tạm giữ",
  Exception: "Ngoại lệ",
  Short: "Thiếu",
  Discrepancy: "Chênh lệch",
  Quarantine: "Cách ly",
  Blocked: "Bị chặn",
  BLOCKED: "Tạm chặn",
  "Low stock": "Sắp hết hàng",
  "Awaiting Confirmation": "Chờ xác nhận",
  "Verification Failed": "Xác minh thất bại",
  Escalated: "Đã leo thang",
  Inbound: "Hàng vào",
  Reopened: "Mở lại",
  "Waiting on Customer": "Chờ khách",
  "Waiting on Internal": "Chờ nội bộ",
  "Partially Paid": "Thanh toán một phần",
  Warning: "Cảnh báo",
  "Pending Payment": "Chờ thanh toán",
  "Ready to Fulfill": "Sẵn sàng thực hiện",
  "Return Requested": "Yêu cầu trả hàng",
  "Pending Verification": "Chờ xác minh",
  "Draft Proposal": "Đề xuất nháp",
  // Danger
  Cancelled: "Đã huỷ",
  Rejected: "Từ chối",
  Failed: "Thất bại",
  Disputed: "Tranh chấp",
  "Delivery Failed": "Giao thất bại",
  Returned: "Đã trả",
  Returning: "Đang trả",
  Suspended: "Tạm ngưng",
  "Out of stock": "Hết hàng",
  Fail: "Không đạt",
  Obsolete: "Lỗi thời",
  OBSOLETE: "Ngừng dùng",
  "Payment Failed": "Thanh toán thất bại",
  Unpaid: "Chưa thanh toán",
  Timeout: "Hết thời gian",
  // Neutral
  Draft: "Nháp",
  Created: "Đã tạo",
  Pending: "Chờ xử lý",
  "Label Created": "Đã tạo nhãn",
  Suggested: "Gợi ý",
  Guest: "Khách vãng lai",
  New: "Mới",
  Requested: "Đã yêu cầu",
  // Muted
  Closed: "Đã đóng",
  Inactive: "Không hoạt động",
  Blacklisted: "Danh sách đen",
  Hidden: "Ẩn",
  Unpublished: "Chưa xuất bản",
  Anonymized: "Đã ẩn danh",
  Merged: "Đã gộp",
  Voided: "Đã vô hiệu",
  Superseded: "Đã thay thế",
  Empty: "Trống",
  Full: "Đầy",
  Disabled: "Vô hiệu hóa",
  Archived: "Lưu trữ",
  Discontinued: "Ngừng kinh doanh",
  Abandoned: "Bỏ dở",
  // Special
  Refunded: "Đã hoàn tiền",
  "Partially Refunded": "Hoàn tiền một phần",
};
