export const INVENTORY_COPY = {
  title: "Tổng quan tồn kho",
  subtitle: "Dữ liệu minh họa · Chưa kết nối hệ thống tồn kho",
  empty: "Chưa có dữ liệu mẫu",
  error: "Không tải được dữ liệu minh họa",
  retry: "Thử lại",
  noResults: "Không tìm thấy tồn kho phù hợp",
  clearFilters: "Xóa bộ lọc",
  mockTableNote: "Tìm kiếm, lọc và phân trang trên dữ liệu minh họa",
  selectStockLevel: "Chọn một dòng tồn kho để xem stock item",
  stockItemError: "Không tải được stock item minh họa",
  noStockItems: "Chưa có stock item cho SKU và kho này",
  fefoDisplayNote: "Hạn dùng sớm hiển thị trước; chưa có hạn dùng ở cuối",
  unknownStatus: "Chưa có trạng thái",
  unknownCondition: "Chưa có tình trạng",
  lookupAtp: "Tra ATP",
  atpPrompt: "Nhập SKU và chọn kho để tra ATP minh họa",
  atpLoading: "Đang tra ATP",
  atpError: "Không tra được ATP minh họa",
  atpNotFound: "Không tìm thấy kết quả cho SKU và kho này",
  atpZero: "ATP bằng 0",
  sections: [
    { id: "stock-levels", title: "Stock Levels" },
    { id: "stock-items", title: "Stock Items" },
    { id: "atp", title: "ATP Lookup" },
    { id: "reservations", title: "Reservations" },
  ],
  noLot: "Chưa có số lô",
  noExpiry: "Chưa có hạn dùng",
} as const;
